version: "3.4"
services:
  application-recip:
    image: bakayarusama/application-recip:1.0.19
    container_name: application-recip
    
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=Debug
        - plateform=windows/amd64
    ports: 
      - 2222:8080
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationVersion: 1.0.19

      MSConfigurationSettings__OdataBaseUrl: "https://ms-configuration-local.brendan-giraudet.com/odata"
      
      MSRecipSettings__OdataBaseUrl: "https://ms-recip-local.brendan-giraudet.com/odata"
      
      MSNotificationSettings__OdataBaseUrl: "https://ms-notification-local.brendan-giraudet.com/odata"
      
      RabbitMqQueueName: "application-recip"
      
      Notifications__PollingInterval: "10000"
      
    restart: always